import{a as b,S as L,i as u}from"./assets/vendor-D2eHbU-E.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const v="47095841-45755c038ed861ac306bdd605",C="photo",S="horizontal",w=!0,g=15,B="https://pixabay.com/api/";async function E(t,e){var o;const a=P(t,e).toString(),n=`${B}?${a}`;return((o=(await b.get(n)).data)==null?void 0:o.hits)??[]}function P(t,e){return new URLSearchParams({q:t,key:v,page:e,image_type:C,orientation:S,per_page:g,safesearch:w})}const i=document.querySelector(".gallery"),D=[{label:"Likes",field:"likes"},{label:"Views",field:"views"},{label:"Comments",field:"comments"},{label:"Downloads",field:"downloads"}];function s(t,e){e?t.classList.remove("hidden"):t.classList.add("hidden")}function I(){i.innerHTML="",s(i,!1)}function O(t){const e=i.children.item(g*(t-1));e==null||e.scrollIntoView({inline:"start",behavior:"smooth"})}function R(t){const e=document.createElement("div");e.innerHTML=t.map($).join(""),Array.from(e.children).length>0&&(s(i,!0),i.append(...Array.from(e.children)))}function $(t){const e=t.previewURL,a=t.largeImageURL,n=t.tags;return`
    <a class="gallery-item" href="${a}">


    <img class="gallery-item-image" alt="${n}" src="${e}"/>
    <div class="gallery-item-details-container">
      ${D.map(r=>q(r.label,t[r.field])).join("")}
    </div>

    </a>`}function q(t,e){return`
    <div class="gallery-item-details-element">
      <span class="label">${t}</span>
      <span class="value">${e}</span>
    </div>`}const p=document.getElementById("search-form"),U=document.getElementById("search-input"),l=document.getElementById("load-more"),f=document.querySelector(".loader"),A=new L(".gallery-item",{captionsData:"alt",captionDelay:250,fadeSpeed:1e3}),h=1;let c=h,m="";async function y(t,e,a){s(f,!0),a&&I();try{const n=await E(t,e);s(f,!1),R(n),c=e,m=t,A.refresh(),n.length===0?(c===1?u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",iconColor:"#FFF",titleColor:"#FFF",messageColor:"#FFF",backgroundColor:"#EF4040",progressBarColor:"#B51B1B"}):u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",iconColor:"#FFF",titleColor:"#FFF",messageColor:"#FFF",backgroundColor:"#0099FF",progressBarColor:"#0071BD"}),s(l,!1)):(s(l,!0),O(c))}catch{s(f,!1),u.error({message:"Request failed, please try again later",position:"topRight",iconColor:"#FFF",titleColor:"#FFF",messageColor:"#FFF",backgroundColor:"#EF4040",progressBarColor:"#B51B1B"})}}function F(t){U.value=t}function T(t){var r,o;t.preventDefault();const e=new FormData(p);let n=((o=(r=Object.fromEntries(e).query)==null?void 0:r.trim)==null?void 0:o.call(r))??"";F(n),n&&(s(l,!1),y(n,h,!0))}function V(){F(m),s(l,!1),y(m,c+1,!1)}function M(){p.addEventListener("submit",T),l.addEventListener("click",V)}M();
//# sourceMappingURL=index.js.map
